import {test,expect} from '@playwright/test';
import {createHash} from 'node:crypto';
const section=(page:any,name:string)=>page.getByRole('navigation',{name:'Infotainment sections'}).getByRole('button',{name,exact:true}).click();
const view=(page:any,name:string)=>page.getByRole('navigation',{name:'Camera presets'}).getByRole('button',{name:new RegExp(name+'$')}).click();
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
test('desktop production: cabin, presets, simulations and every DriveOS section',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
 await page.goto('/');await expect(page.getByText('COCKPIT ONLINE',{exact:true})).toBeAttached({timeout:30000});await expect(page.locator('.loader')).toHaveCount(0);await expect(page.locator('canvas')).toBeVisible();await page.screenshot({path:'test-results/desktop-driver.png'});
 await section(page,'Performance');await page.getByLabel('Vehicle speed',{exact:true}).fill('130');await page.getByLabel('Engine RPM',{exact:true}).fill('6000');await page.getByRole('combobox',{name:'Drive mode',exact:true}).selectOption('Sport+');await expect(page.locator('.sim-number').first()).toContainText('130');await expect(page.locator('.sim-number.rpm')).toContainText('6,000');await view(page,'Cluster');await page.waitForTimeout(1400);const before=hash(await page.locator('canvas').screenshot());await page.getByLabel('Vehicle speed',{exact:true}).fill('220');await page.waitForTimeout(600);expect(hash(await page.locator('canvas').screenshot())).not.toBe(before);await page.screenshot({path:'test-results/cluster.png'});
 await page.getByRole('button',{name:'Start drive',exact:true}).click();await expect(page.getByText('SIMULATION ACTIVE')).toBeVisible();await page.waitForTimeout(600);await page.getByRole('button',{name:'Pause drive',exact:true}).click();
 await section(page,'Climate');await page.getByRole('button',{name:'Increase driver temperature',exact:true}).click();await expect(page.locator('.temperatures')).toContainText('21.5');await page.getByRole('switch',{name:'Air conditioning',exact:true}).click();await expect(page.getByRole('switch',{name:'Air conditioning',exact:true})).toHaveAttribute('aria-checked','false');await page.getByLabel('Seat heating',{exact:true}).fill('2');await page.getByLabel('Seat ventilation',{exact:true}).fill('2');await expect(page.getByLabel('Seat heating',{exact:true})).toHaveValue('0');
 await section(page,'Media');await page.getByRole('button',{name:'Play music',exact:true}).click();await page.getByRole('button',{name:'Next track',exact:true}).click();await expect(page.locator('.track-title')).toContainText('Alpine Frequencies');await page.getByRole('button',{name:'Favorite track',exact:true}).click();await expect(page.getByRole('button',{name:'Favorite track',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Pause music',exact:true}).click();
 await section(page,'Navigation');await page.getByRole('button',{name:'Pause guidance',exact:true}).click();await expect(page.getByText('Route paused',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Resume guidance',exact:true}).click();
 await section(page,'Phone');await page.getByRole('button',{name:'Connect demo phone',exact:true}).click();await page.getByRole('button',{name:'Alex Morgan',exact:true}).click();await expect(page.getByRole('status')).toContainText('No real call');
 await section(page,'Vehicle');await page.getByLabel('Suspension',{exact:true}).selectOption('Sport+');await expect(page.getByRole('combobox',{name:'Drive mode',exact:true})).toHaveValue('Individual');
 await section(page,'ADAS');await page.getByRole('switch',{name:/Adaptive Cruise/}).click();await expect(page.getByRole('switch',{name:/Adaptive Cruise/})).toHaveAttribute('aria-checked','true');await page.getByRole('button',{name:/Explore sensor coverage/}).click();await page.waitForTimeout(1500);await page.screenshot({path:'test-results/sensor-view.png'});
 await section(page,'Cameras');await page.getByRole('button',{name:'30 cm',exact:true}).click();await expect(page.getByRole('img',{name:/Surround camera demonstration/})).toHaveAttribute('aria-label',/30 centimeters/);await page.getByRole('button',{name:'Rear',exact:true}).click();await expect(page.getByRole('img',{name:/Rear camera demonstration/})).toBeVisible();
 await section(page,'Lighting');await page.getByRole('button',{name:'Jade ambient lighting',exact:true}).click();await page.getByRole('switch',{name:/Night environment/}).click();await view(page,'Passenger');await page.waitForTimeout(1500);await page.screenshot({path:'test-results/ambient-night.png'});
 await section(page,'Settings');await page.getByRole('switch',{name:'Head-up display',exact:true}).click();await expect(page.getByRole('switch',{name:'Head-up display',exact:true})).toHaveAttribute('aria-checked','false');
 for(const c of ['Driver','Dashboard','Infotainment','Cluster','Steering Wheel','Center Console','Passenger','Interior Overview','ADAS','Sensor View']){await view(page,c);await expect(page.locator('.view-caption b')).toHaveText(c);await page.waitForTimeout(120);}
 await view(page,'Interior Overview');await page.waitForTimeout(1500);await page.screenshot({path:'test-results/interior-overview.png'});await view(page,'Driver');await page.waitForTimeout(1400);await page.getByRole('button',{name:'Explore systems',exact:true}).click();await page.getByRole('button',{name:'Explore Climate',exact:true}).click();await expect(page.locator('.info-card')).toContainText('Dual-zone climate');await page.getByRole('button',{name:'Close technical information',exact:true}).click();
 const canvas=page.locator('canvas'),box=(await canvas.boundingBox())!;const snapshot=hash(await canvas.screenshot());await page.mouse.move(box.x+box.width*.5,box.y+box.height*.45);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.52,{steps:8});await page.mouse.up();await page.mouse.wheel(0,-80);await page.waitForTimeout(500);expect(hash(await canvas.screenshot())).not.toBe(snapshot);
 await page.getByRole('button',{name:'Open help',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);expect(errors).toEqual([]);
});
test('mobile portrait: usable touch canvas, menus and persisted preferences',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.TEST_BASE_URL||'http://127.0.0.1:4173');await expect(page.getByText('COCKPIT ONLINE',{exact:true})).toBeAttached({timeout:30000});await page.screenshot({path:'test-results/mobile-cockpit.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByRole('button',{name:'Open DriveOS',exact:false}).tap();await section(page,'Lighting');await page.getByRole('button',{name:'Glacier ambient lighting',exact:true}).tap();await expect(page.getByRole('button',{name:'Glacier ambient lighting',exact:true})).toHaveClass('active');await page.screenshot({path:'test-results/mobile-driveos.png'});await page.getByRole('button',{name:'Close DriveOS',exact:true}).tap();const cdp=await context.newCDPSession(page);await cdp.send('Input.synthesizePinchGesture',{x:180,y:390,scaleFactor:1.15,gestureSourceType:'touch'});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y:390}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:230,y:420}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.reload();await expect(page.getByText('COCKPIT ONLINE',{exact:true})).toBeAttached({timeout:30000});await page.getByRole('button',{name:'Open DriveOS',exact:false}).tap();await section(page,'Lighting');await expect(page.getByRole('button',{name:'Glacier ambient lighting',exact:true})).toHaveClass('active');expect(errors).toEqual([]);await context.close();
});
