import {lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ChevronDown,ChevronRight,Expand,Focus,HelpCircle,Layers,Menu,Moon,Play,RotateCcw,Sun,X,Pause,ShieldCheck,Radio,VolumeX,Wind} from 'lucide-react';
import {initialState,cameras,modes,sections,tracks,modeColor,type State,type Section,type Camera} from './systems/model';
import {systems,type System} from './data/systems';
import {DrivePanel,sectionIcons} from './ui/DrivePanel';
import {useCabinAudio} from './systems/audio';
const Viewport=lazy(()=>import('./cockpit/Viewport'));
const key='aeron-cockpit-v1';
function restore():State{try{const saved=JSON.parse(localStorage.getItem(key)||'{}');return {...initialState,...Object.fromEntries(['ambient','brightness','driverTemp','passengerTemp','hud','night','quality'].filter(k=>typeof saved[k]===typeof initialState[k as keyof State]).map(k=>[k,saved[k]]))};}catch{return {...initialState};}}
export default function App(){
 const [s,setState]=useState<State>(restore),[section,setSection]=useState<Section>('Home'),[camera,setCamera]=useState<Camera>('Driver'),[cameraRevision,setCameraRevision]=useState(0),[hotspots,setHotspots]=useState(false),[info,setInfo]=useState<System|null>(null),[toast,setToast]=useState(''),[help,setHelp]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[ready,setReady]=useState(false);const phase=useRef(0),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const notify=useCallback((text:string)=>{setToast(text);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4200);},[]);
 const patch=useCallback((p:Partial<State>)=>setState(s=>({...s,...p})),[]);
 const view=useCallback((c:Camera)=>{setCamera(c);setCameraRevision(n=>n+1);setMobileOpen(false);},[]);
 const select=useCallback((v:Section)=>{setSection(v);setInfo(null);},[]);
 useCabinAudio(s,notify);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify({ambient:s.ambient,brightness:s.brightness,driverTemp:s.driverTemp,passengerTemp:s.passengerTemp,hud:s.hud,night:s.night,quality:s.quality}));}catch{/* Private storage can be unavailable. */}},[s.ambient,s.brightness,s.driverTemp,s.passengerTemp,s.hud,s.night,s.quality]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.hidden)return;setState(v=>{if(!v.running&&!v.playing&&!v.lapRunning)return v;const next={...v};if(v.running){phase.current+=.25;const speed=Math.round(70+Math.sin(phase.current*.13)*36+Math.sin(phase.current*.37)*8);next.speed=speed;next.gear=String(Math.max(1,Math.min(8,Math.floor(speed/24)+1)));next.rpm=Math.round((1700+speed%24*125)/50)*50;}
 if(v.playing){next.progress=v.progress+.25;if(next.progress>=tracks[v.track].duration){next.track=(v.track+1)%tracks.length;next.progress=0;}}if(v.lapRunning)next.lapTime=v.lapTime+.25;return next;});},250);return()=>clearInterval(timer);},[]);
 useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'){setHelp(false);setInfo(null);setMobileOpen(false);}};window.addEventListener('keydown',esc);return()=>{window.removeEventListener('keydown',esc);if(toastTimer.current)clearTimeout(toastTimer.current);};},[]);
 const onAction=useCallback((action:string)=>{
 const shortcuts:Record<string,()=>void>={Play:()=>setState(v=>({...v,playing:!v.playing})),Media:()=>{select('Media');setMobileOpen(true);},Previous:()=>setState(v=>({...v,track:(v.track+2)%3,progress:0})),Next:()=>setState(v=>({...v,track:(v.track+1)%3,progress:0})),Volume:()=>setState(v=>({...v,volume:Math.min(100,v.volume+5)})),Cruise:()=>setState(v=>({...v,adas:{...v.adas,'Adaptive Cruise':!v.adas['Adaptive Cruise']}})),Voice:()=>notify('Voice assistant demo: choose a system from DriveOS to explore it.'),Mode:()=>setState(v=>({...v,mode:modes[(modes.indexOf(v.mode)+1)%modes.length]})),Gear:()=>setState(v=>({...v,gear:v.gear==='P'?'1':'P'})),Upshift:()=>setState(v=>({...v,gear:String(Math.min(8,(parseInt(v.gear)||0)+1))})),Downshift:()=>setState(v=>({...v,gear:String(Math.max(1,(parseInt(v.gear)||2)-1))}))};
 if(shortcuts[action]){shortcuts[action]();if(!['Media','Voice'].includes(action))notify(`${action} control applied`);return;}
 const lookup:Record<string,number>={Cluster:0,Infotainment:1,HUD:2,'Steering Wheel':3,'Drive Selector':4,Climate:5,ADAS:6,Lighting:7,Cameras:8,'Sensor View':9};const item=systems[lookup[action]??0];setInfo(item);setSection(item.section);view(item.camera);
 },[notify,select,view]);
 const reset=()=>{setState({...initialState});setSection('Home');setInfo(null);view('Driver');notify('Cabin preferences reset.');};
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else notify('Use landscape orientation for a larger cockpit view on this device.');}catch{notify('Fullscreen is not available in this browser.');}};
 return <div className="app" style={{'--accent':modeColor(s.mode)} as React.CSSProperties}>
 <header className="topbar"><a className="wordmark" href="#" onClick={e=>{e.preventDefault();select('Home');view('Driver');}}><span className="brand-glyph">Λ</span><span>AERON<small>AUTOMOTIVE LAB</small></span></a><div className="project-heading"><span>3D AUTOMOTIVE</span><strong>DASHBOARD LAB<span className="version">01</span></strong></div><div className="header-actions"><span className="live-status"><i/>{ready?'COCKPIT ONLINE':'INITIALIZING'}</span><button className="icon-button" aria-label={s.night?'Switch to daylight':'Switch to night'} title="Day / night" onClick={()=>patch({night:!s.night})}>{s.night?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button" aria-label="Enter fullscreen" title="Fullscreen" onClick={fullscreen}><Expand size={18}/></button><button className="icon-button" aria-label="Open help" title="Help" onClick={()=>setHelp(true)}><HelpCircle size={18}/></button></div></header>
 <main className="workspace"><section className="explorer" aria-label="Cockpit explorer"><Suspense fallback={<div className="loader"><h2>Preparing cockpit renderer…</h2></div>}><Viewport state={s} section={section} camera={camera} cameraRevision={cameraRevision} hotspots={hotspots} highlight={info?.camera??null} onAction={onAction} onReady={()=>setReady(true)}/></Suspense>
 <div className="scene-heading"><div className="eyebrow"><span/> THE PERFORMANCE COLLECTION</div><h1>AERON <em>GT.</em></h1><p>Explore the technology inside<br/>a modern performance cockpit.</p><div className="scene-tags"><span>ORIGINAL CONCEPT</span><span>3D INTERACTIVE</span></div></div>
 <div className="scene-tools"><button aria-pressed={hotspots} className={hotspots?'active':''} onClick={()=>setHotspots(!hotspots)} title="Toggle interactive hotspots"><Focus size={17}/><span>Explore systems</span></button><button onClick={()=>{view(camera);notify('Camera reset to preset.');}} title="Reset camera" aria-label="Reset camera"><RotateCcw size={16}/></button></div>
 {hotspots&&<div className="system-directory"><small>SYSTEM DIRECTORY</small>{systems.map((item,i)=><button key={item.name} onClick={()=>{setInfo(item);setSection(item.section);view(item.camera);}}><span>{String(i+1).padStart(2,'0')}</span>{item.name}<ChevronRight size={12}/></button>)}</div>}
 {(camera==='Sensor View'||camera==='ADAS')&&<div className="sensor-legend"><span><i style={{background:'#ff9259'}}/>Front radar</span><span><i style={{background:'#7facbd'}}/>Front camera</span><span><i style={{background:'#b0a0d1'}}/>Blind spot radar</span><span><i style={{background:'#85bca7'}}/>Surround / near field</span><small>Schematic coverage · not to scale</small></div>}
 <div className="view-caption"><span className="view-index">{String(cameras.indexOf(camera)+1).padStart(2,'0')} / 10</span><div><b>{camera}</b><small>Drag to explore · Scroll to zoom · Select a system</small></div></div>
 <div className="simulation-bar"><div className="sim-status"><span className={s.running?'pulse-dot':'idle-dot'}/><span>{s.running?'SIMULATION ACTIVE':'SIMULATION STANDBY'}</span></div><div className="sim-number"><b>{s.speed}</b><small>km/h</small></div><div className="sim-number rpm"><b>{s.rpm.toLocaleString()}</b><small>rpm</small></div><div className="gear-chip">{s.gear}</div><button className="demo-button" onClick={()=>patch({running:!s.running})}>{s.running?<Pause size={14}/>:<Play size={14}/>}<span>{s.running?'Pause drive':'Start drive'}</span></button></div>
 <button className="mobile-drive" onClick={()=>setMobileOpen(true)}><Layers size={17}/> Open DriveOS <ChevronRight size={16}/></button>
 </section>
 <aside className={`drive-panel ${mobileOpen?'mobile-open':''}`} aria-label="DriveOS control panel"><div className="drive-header"><span>Drive<span className="orange">OS</span><sup> / 1.0</sup></span><div><span className="connection-dot"/><small>VEHICLE CONNECTED</small><button className="mobile-close icon-button" aria-label="Close DriveOS" onClick={()=>setMobileOpen(false)}><X size={18}/></button></div></div><nav className="section-nav" aria-label="Infotainment sections">{sections.map(name=>{const Icon=sectionIcons[name];return <button key={name} title={name} aria-label={name} aria-current={section===name?'page':undefined} className={section===name?'active':''} onClick={()=>select(name)}><Icon size={17}/><span>{name}</span></button>;})}</nav><div className="panel-content" key={section}><DrivePanel state={s} section={section} patch={patch} select={select} view={view} notify={notify} reset={reset}/></div><div className="climate-footer"><button onClick={()=>select('Climate')}><Wind size={16}/><b>{s.driverTemp}°</b><small>DRIVER</small></button><button onClick={()=>select('Climate')} className="climate-ac">{s.ac?'A/C ON':'A/C OFF'}</button><button onClick={()=>select('Climate')}><b>{s.passengerTemp}°</b><small>PASSENGER</small></button></div></aside></main>
 <section className="bottom-dock"><div className="camera-label"><span>POINT OF VIEW</span><b><Focus size={15}/> Camera presets</b></div><nav className="camera-presets" aria-label="Camera presets">{cameras.map((c,i)=><button key={c} aria-pressed={camera===c} className={camera===c?'active':''} onClick={()=>view(c)}><span>{String(i+1).padStart(2,'0')}</span>{c}</button>)}</nav><div className="drive-mode"><small>DRIVE MODE</small><label><select aria-label="Drive mode" value={s.mode} onChange={e=>patch({mode:e.target.value as State['mode']})}>{modes.map(m=><option key={m}>{m}</option>)}</select><ChevronDown size={14}/></label></div></section>
 <footer className="footer"><span>Created by <strong>Amir Saeid Dehghan</strong></span><span>ENGINEERED TO EXPLORE<span className="footer-line"/>ORIGINAL FICTIONAL VEHICLE</span><a href="https://github.com/saaeiddev/3D-Automotive-Dashboard-Lab" target="_blank" rel="noreferrer">PROJECT SOURCE <ArrowUpRight size={12}/></a></footer>
 {info&&<div className="info-card"><button className="icon-button close" aria-label="Close technical information" onClick={()=>setInfo(null)}><X size={17}/></button><span className="eyebrow">SYSTEM INSIGHT</span><h2>{info.name}</h2><p className="info-purpose">{info.purpose}</p>{[['HOW IT WORKS',info.how],['MAIN COMPONENTS',info.components],['VEHICLE LOCATION',info.location],['DRIVER BENEFIT',info.benefit],['LIMITATIONS',info.limitations]].map(([label,value])=><div key={label}><small>{label}</small><p>{value}</p></div>)}</div>}
 {toast&&<div className="toast" role="status">{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={14}/></button></div>}
 {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="help-modal" role="dialog" aria-modal="true" aria-label="Cockpit controls" onClick={e=>e.stopPropagation()}><button autoFocus className="icon-button close" aria-label="Close help" onClick={()=>setHelp(false)}><X size={20}/></button><span className="eyebrow">WELCOME TO THE LAB</span><h2>Take the driver’s seat.</h2><p>Explore an original performance cockpit and the systems behind it.</p><dl><dt>Drag / one finger</dt><dd>Orbit the selected view</dd><dt>Scroll / pinch</dt><dd>Zoom toward the selected component</dd><dt>Explore systems</dt><dd>Show 3D hotspots and technical explanations</dd><dt>Start drive</dt><dd>Run a simulated drive with animated speed, gear and RPM</dd><dt>DriveOS</dt><dd>Control media, climate, lighting and assistance</dd><dt>Camera presets</dt><dd>Move smoothly between ten viewpoints</dd></dl><p className="note">All vehicle behavior, navigation, cameras and telemetry are educational simulations. This project is not affiliated with any automotive manufacturer.</p><button className="primary full" onClick={()=>setHelp(false)}>Explore the cockpit <ArrowUpRight size={16}/></button></section></div>}
 </div>;
}
